### ISSUE TITLE
Integrating with frameworks?

### ISSUE THREAD

**Issue by Exanlv** [notback-php/notback#1]
Is there any intended way to integrate with a framework?

I quite like the syntax notback provides, but using some kind of framework with routing has my preference.

Tried throwing it into Slim, somewhat works but not really in the way you're supposed to do it.

```php
$app->get('/', function (Request $request, Response $response, $args) {
    $response->getBody()->write(
        Page('Hi there')
    );

    return $response;
});
```

The problem here is that you'd usually pass `$response->getBody()->write()` a string, but `Page` echos out content directly, rather than allowing it to return a string.

Obviously this can be accomplished using output buffering, but I wouldn't say that's a very clean solution.

Unless you already have something in mind or in place for this, I'd like to suggest making `Page` return a string, rather than echoing content directly onto the page. With this, the hello world example would turn into this:

```php
<?php

require 'vendor/autoload.php';

echo Page(
    "Hello World!"
);
```

**Comment by Exanlv** [comment]
In case you like my suggestion, created a PR for it: https://github.com/notback-php/notback/pull/2

**Comment by Degn** [comment]
@Exanlv really cool idea and thank you for your effort! 

As you might see, I love minimalism and I really like the simplicity of the `Page` as it is... BUT I see your point in having something to return for integrations :) 

My suggestion is to make a function in the middle called `PageContent()` which would be the `Page`, that you suggest, that returns the content as a string. Then the `Page` will just be : 

```
function Page() {
    echo PageContent(...);
}
``` 
and then the `PageContent` can be used for integrations etc. 

Could that be a solution? :)

**Comment by Exanlv** [comment]
Thought about that too, Ill update my PR when I get to a desk in ~20 minutes

**Comment by Exanlv** [comment]
Have by now updated the PR, forgot to mention it here

**Comment by Degn** [comment]
Well done and thank you for your work! :)
